# Generated by Django 5.2.7 on 2025-10-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
    ]
